#version: "3.9"

services:

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener
      POSTGRES_DB: shortener
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shortener" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - appnet
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      args:
        - UID=1001
        - GID=1001
    user: "1001:1001"
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://shortener:shortener@db:5432/shortener
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
      API_KEY: bPx0V9hw8h4Cs3xsfvZDJ2sEkrPAwU3yRBkb2MpN3TQ=
    networks:
      - appnet
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen(\"http://localhost:8000/\").getcode() == 200 else 1)'" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  appnet:
    driver: bridge

volumes:
  db-data: {}
  redis-data: {}
